# Site settings
title: Vijay Prakash
#email: vijay.prakash@ucalgary.ca
#url: https://github.com/jeromelachaud/freelancer-theme
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Business Analysis - Exploratory Data Analysis - Data Visualization - Financial Analysis <br/><br/> Power BI - SQL - JIRA - MS Visio - MS Excel - VBA - R"
meta_author: Prakash Vijay

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 58a7c7 #80B3FF
  primary-rgb: "88,167,199" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
 # - title: linkedin
  #  url: put linkedin here
#  - title: envelope
  #  icon: envelope
 #   url: mailto:put email here

# Credits content
credits: 'Credit: Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Maintained By
maintained_by: 'This page was generated by GitHub Pages. Maintained by Vijay Prakash.'
# site.personal_files
site.personal_files:
 - url: personal/files/htmlSample1.html
 - url: personal/files/htmlSample1.html
 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
